### ISSUE TITLE
Proposal: Rename repository

### ISSUE THREAD

**Issue by thegecko** [eclipse-cdt-cloud/cdt-gdb-adapter#124]
As debug adapters adhere to the Debug Adapter Protocol, they aren't necessarily tied to a specific IDE or plugin.

In fact this adapter is in use by folks for CDT-, VS Code- and Theia- based applications.

The current naming of this repository/adapter can be confusing and easily dismissed as something only for use with the eclipse CDT project.

Can I propose we rename this project to something less specific to reflect the portable nature of the functionality and aid with discoverability?

e.g.

- mi-debug-adapter
- gdb-debug-adapter
- cpp-gdb-adapter
- ...

cc @marechal-p @dschaefer @jonahgraham

**Comment by jonahgraham** [comment]
Interesting question. This has been a regular issue in the past in relation to whether CDT is going to evolve to be more generic tools for C/C++ development for other use cases or not. As a point of comparison, the https://github.com/eclipse/eclipse.jdt.ls still use the JDT name even though it is not used in Eclipse IDE - but perhaps not an apt comparison because it uses the JDT source too, whereas we are just using the CDT expertise/experience rather than the literal source.

**Comment by thegecko** [comment]
> This has been a regular issue in the past in relation to whether CDT is going to evolve

It's wider than than just CDT. I'm aware of at least two other IDEs which use this adapter and are entirely unrelated to CDT.

I'd also be keen to avoid it in the code, too if possible:
https://github.com/eclipse-cdt/cdt-gdb-adapter/blob/master/src/GDBDebugSession.ts#L79

**Comment by dschaefer** [comment]
Of course, CDT isn't an IDE, it's a project. It contributes to the C/C++ IDE for Eclipse along with many other IDE's based on Eclipse. Also, people also take the CDT parser/indexer and stick in different places. So it isn't that crazy a thought to consider this part of the CDT project that contributes to many IDEs some not based on Eclipse.

But I'm just a ghost from the grave ;)

**Comment by thegecko** [comment]
> CDT isn't an IDE, it's a project

I stand corrected, perhaps it makes more sense if I state that this debug adapter isn't just used by CDT nor the Eclipse IDE. I don't use it with either :)
