### ISSUE TITLE
How to decrease the amout of gdb log messages shown in Debug Console?

### ISSUE THREAD

**Issue by jonah-iden** [eclipse-cdt-cloud/cdt-gdb-adapter#337]
Hi,
When trying to debug a program with this adapter in vscode im seeing lots of messages in the log like `Reading C:\Program Files\mingw64\bin\libgcc_s_seh-1.dll from remote target...` or when hitting a breakpoint `Thread 1 hit Breakpoint 1,...`. 

Is there a way to only show messages from the debugged program in the Deug Console? 
using `-batch-silent` seems to break the adapter. But i'm not very familiar with GDB so maybe im overlooking something?

**Comment by jonahgraham** [comment]
@jonah-iden thanks for the question.

I think it is expected that `-batch-silent` breaks the adapter because it omits key information the UI needs - the GDB docs say:

> This is much quieter than ‘-silent’ and would be useless for an interactive session.

However, if you are running on a Linux host and using GDB >= 7.12 you may find the `openGdbConsole` setting set to true useful in this situation as you may be able to silence the CLI side or things and leave MI running normally.

There could also be some new options added to the adapter to silence these messages.

I do have one follow up question - is there some output from GDB in the Debug Console that you do want to see that these extra messages are hiding from you?

**Comment by jonah-iden** [comment]
@jonahgraham Thanks alot for the answer. I'll see if i can contribute something in the future

It's not that its directly hiding something. It's mostly just about UX. When using this in an IDE and hitting a breakpoint seeing a "hit breakpoint" message is just unneccessary and fills up the output, so it may be slightly harder to spot some other output.
It's not a giant problem.

**Comment by jonahgraham** [comment]
Ahh. I understand what you mean. I think the best place to address this may be in GDB itself - adding some additional conditional like perhaps "is UI connected" type logic to the [maybe_print_thread_hit_breakpoint](https://github.com/bminor/binutils-gdb/blob/0e15fd3d54f8e70015f31226eaa87f9eaa536fbd/gdb/breakpoint.c#L5006) - doing any of this in the adapter would mean having to interpret the non-MI output to filter out unwanted text.
