### ISSUE TITLE
How to publish the native bits for use inside a VS Code extension

### ISSUE THREAD

**Issue by paul-marechal** [eclipse-cdt-cloud/cdt-gdb-adapter#78]
I recently added a bit of native code in order to open ptys, needed by GDB for it to open both a regular console and an MI channel at the same time.

It works perfectly fine when using the debug adapter as an npm dependency, as it will be built for the running machine on installation.

Problem arises when we want to pack everything in a self contained archive to distribute as a VS Code extension. At that point everything must be compiled/transpiled.

Had a discussion with @simark about it, so far I got two ideas from it:

#### 1. Move the native out of the adapter, only depend on the prebuilt binaries

Basically, we could have a new npm package that wouldn't be published, but used to build the binaries.
Then we can have the debug adapter just depend on some CI output artifacts that it would download from the CI jobs/servers. Artifacts in this case would be the built native code for each platform.

Pros:
- Nothing to install on user machine (nothing more than the VS Code extension).

Cons:
- Have to setup the thing with the CI on 3 platforms, have the binaries downloaded in the adapter (postinstall?), and make a conditional require based on the OS to pick the right one.

#### 2. Make an utility script to spawn TTYs

The other way around would be to publish a package on NPM that would only be responsible of setting up the TTYs, to be invoked as some system bin/script. The GDB console feature would only be supported if user has this package installed like `npm install -g create-pty`.

Because passing fds around seems weird, the script would open 2 pairs of master/slave in order to easily share the resources, making some kind of bridge:

```
+------------+     +---------------------+     +------------+
|            |     |                     |     |            |
|     DA     |     |     create-pty      |     |   GDB MI   |
|            |     |                     |     |            |
| /dev/pts/X +-----+ masterX <-> masterY +-----+ /dev/pts/Y |
|            |     |                     |     |            |
+------------+     +---------------------+     +------------+
```
Pros:
- No CI involved, native code is built on client machine.

Cons:
- Must be installed before hand.

---

Looking for feedback on this :)

**Comment by dschaefer** [comment]
Earlier this year I created a native addon on to manage system trace files our RTOS generates. To build it I have a separate build script to build the native code. It uses CMake which I am familiar with and I put the resulting binary in a platform specific directory in the extension. I then load it using a dynamic require using node's process.platform variable to pick the directory.

I then set up CI jobs for each of the platforms (three in our case, all 64-bit) to just build the binaries. In the extension build job I just copied them over.

In development, I had a build:native and a build:extension (and a build:webview for webpacky stuff) and then did a run-all-p build:* to build them all as needed.

Not saying this is the best way. The resulting extension ends up with binaries for all the platforms in the package when at install time you only need the one. And we may want to stick with node-gyp instead of my crazy CMake stuff.

Anyway, I'd make this a client concern. The adapter just needs to deliver the source and gyp files as we have them now. Each client might have it's own strategy on how it wants to package the binaries.

**Comment by marechal-p** [comment]
> Anyway, I'd make this a client concern. The adapter just needs to deliver the source and gyp files as we have them now. Each client might have it's own strategy on how it wants to package the binaries.

Yes, but then how does one pick between fetching the binaries for each platform from somewhere, to building it locally?

I have been trying things, and so far it is a bit of a pain.
https://github.com/marechal-p/cdt-gdb-adapter/commit/d97d37286fb78b1887dac2d165cc6eec0e4b6804

With this commit, the adapter no longer automatically builds the native part. Instead, it would be the responsability of the client to run `npm explore cdt-gdb-adapter yarn build:native`. Tasty right?

And in the case we want to fetch things from CI jobs, we could expose one more command, like `npm explore cdt-gdb-adapter yarn build:fetch-from-ci`.

Oh and from the tests I ran, by linking `cdt-gdb-adapter` into `cdt-gdb-vscode`, for some reason `node-gyp` tries to run despite `binding.gyp` not being at the root in my commit, and hence fails. So you got to run `yarn --ignore-scripts`.

The goal I was trying to achieve was to allow the two options of getting the binary: either by building locally or grabbing it from somewhere. I got close, despite the few issues I mentioned above.

Any thoughts on this?

**Comment by dschaefer** [comment]
Over time I expect to add other native libraries from npm. For example there's a really good usb detection library we could use to help with setting up serial debugging. We have no control over how that builds. And I'm not sure how to properly deal with that.

At any rate, we're running into VS Code's lack of handling of platform specific bits in the extensions. Eclipse figured this out a long time ago where we use plug-in fragments that only get installed on the platforms they support. That's also why it should probably be a client concern since Eclipse has this figured out, but VS Code hasn't yet.

For now, I'd leave gyp where it is. Since we would be dynamically require'ing we can make smart decisions on where to find the native library. For example, if it's the build/Release (or Debug) directory, we're in development mode and we'd load that. We'd filter that directory from the vsix package so in production, we can use the process.platform to find the right *.node file for the current platform. As an example...

**Comment by dschaefer** [comment]
One extreme solution would be to have separate vsix files for every platform.

Otherwise, we may need to conjure up some npm module loading magic to make this work for all scenarios.

**Comment by dschaefer** [comment]
Just looking at how usb-detection deals with things, it's using the bindings library. Looks like it handles platform specific locations.

**Comment by dschaefer** [comment]
Found this. Looks like the VS Code and Marketplace teams are working on it. https://github.com/Microsoft/vscode/issues/23251

**Comment by dschaefer** [comment]
So it looks like they're going with my extreme solution. It's probably the only one that works well.

What that would mean is that we'd do complete vsix builds on each of the platforms we support. gyp will put things in the right place. And we don't have to change anything other than setting up the CI machines for each platform.

**Comment by marechal-p** [comment]
I see, so do you want to wait for VS Code to address that?

Otherwise, we would need to publish the adpater with every precompiled native binaries:

```
cdt-gdb-adapter/
    native/
        pty-win32-ia32.node
        pty-darwin.node
        pty-linux-ia32.node
        pty-linux-x64.node
    dist/
        ...
    src/
        ...
    ...
```

I was more concerned with the setup in order to have the layout as above.

**Comment by marechal-p** [comment]
Just found https://github.com/mapbox/node-pre-gyp, reading...

**Comment by dschaefer** [comment]
So, no, we would create vsix files for every platform. The vsix files contain the *.node files in the places gyp put them. Again, I'm really trying to leave this to the clients to solve and just have the adapter do the normal node-gyp thing.

BTW, speaking of which, I  had opened this a while ago. https://github.com/eclipse-cdt/cdt-gdb-vscode/issues/19

**Comment by marechal-p** [comment]
> So, no, we would create vsix files for every platform. The vsix files contain the *.node files in the places gyp put them.

Sounds good!

**Comment by jonahgraham** [comment]
This is really an issue for cdt-gdb-vscode, so lets track it there in https://github.com/eclipse-cdt-cloud/cdt-gdb-vscode/issues/19. If and when there is something concrete for cdt-gdb-adapter to change we create new issues.
